export enum tipoTrabajador {
  SEGURIDAD = 'SEGURIDAD INDUSTRIAL',
  MANTENIMIENTO = 'MANTENIMIENTO',
  INGENIERIA = 'INGENIERIA',
  RRHH = 'RECURSOS HUMANOS',
  MARKETING = 'MARKETING',
  OPERARIO = 'OPERARIO',
  TI = 'TI',
  OTROS = 'OTROS',
}
